"""MatterLoop 零第三方运行时依赖内核的稳定公共 API。"""

from matterloop_core.context import (
    ArtifactRef,
    ExecutionResult,
    HumanAction,
    HumanInteractionKind,
    HumanInteractionRecord,
    HumanInteractionRequest,
    HumanResponse,
    IterationRecord,
    LoopCheckpointCodec,
    LoopContext,
    LoopLimits,
    LoopRequest,
    LoopResult,
    Plan,
    PlanStep,
    VerificationResult,
    result_from_context,
)
from matterloop_core.control import (
    ApprovalDecision,
    CompletionAction,
    CompletionDecision,
    RetryAction,
    RetryDecision,
)
from matterloop_core.events import EventHandler, LocalEventPublisher, LoopEvent, LoopEventType
from matterloop_core.exceptions import (
    CheckpointConflictError,
    CheckpointSchemaError,
    ComponentAlreadyRegisteredError,
    ComponentNotFoundError,
    HumanInteractionNotPendingError,
    HumanResponseConflictError,
    InvalidPlanError,
    InvalidPluginError,
    InvalidStateTransitionError,
    LoopNotFoundError,
    LoopNotResumableError,
    LoopRequestConflictError,
    MatterLoopError,
    ResourceLimitExceededError,
)
from matterloop_core.loop import AgentLoop
from matterloop_core.protocols import (
    ApprovalGate,
    CheckpointPreparer,
    CheckpointStore,
    CompletionEvaluator,
    EventPublisher,
    Executor,
    LoopPolicy,
    Planner,
    RetryPolicy,
    Verifier,
)
from matterloop_core.registry import (
    ComponentRegistry,
    ComponentSpec,
    FactoryCatalog,
    PluginDefinition,
)
from matterloop_core.state import LoopStatus, ResumeMode, StopReason, ensure_transition

__all__ = [
    "AgentLoop",
    "ApprovalDecision",
    "ApprovalGate",
    "ArtifactRef",
    "CheckpointSchemaError",
    "CheckpointConflictError",
    "CheckpointPreparer",
    "CheckpointStore",
    "CompletionAction",
    "CompletionDecision",
    "CompletionEvaluator",
    "ComponentAlreadyRegisteredError",
    "ComponentNotFoundError",
    "ComponentRegistry",
    "ComponentSpec",
    "EventHandler",
    "EventPublisher",
    "ExecutionResult",
    "Executor",
    "FactoryCatalog",
    "HumanAction",
    "HumanInteractionKind",
    "HumanInteractionNotPendingError",
    "HumanInteractionRecord",
    "HumanInteractionRequest",
    "HumanResponse",
    "HumanResponseConflictError",
    "InvalidPlanError",
    "InvalidPluginError",
    "InvalidStateTransitionError",
    "IterationRecord",
    "LocalEventPublisher",
    "LoopCheckpointCodec",
    "LoopContext",
    "LoopEvent",
    "LoopEventType",
    "LoopLimits",
    "LoopNotFoundError",
    "LoopNotResumableError",
    "LoopRequestConflictError",
    "LoopPolicy",
    "LoopRequest",
    "LoopResult",
    "LoopStatus",
    "MatterLoopError",
    "Plan",
    "Planner",
    "PlanStep",
    "PluginDefinition",
    "ResumeMode",
    "ResourceLimitExceededError",
    "RetryAction",
    "RetryDecision",
    "RetryPolicy",
    "StopReason",
    "VerificationResult",
    "Verifier",
    "ensure_transition",
    "result_from_context",
]
