"""MCP Session 注入、能力发现与 MatterLoop Tool 适配公共 API。"""

from matterloop_tools.mcp.client import McpServerConnection
from matterloop_tools.mcp.errors import (
    McpCapabilityNotSupportedError,
    McpCatalogStaleError,
    McpConfigurationError,
    McpError,
    McpLifecycleError,
    McpPaginationLimitError,
    McpProtocolError,
    McpRemoteError,
    McpResponseLimitError,
    McpServerNotFoundError,
    McpTimeoutError,
    McpToolNameCollisionError,
    McpTransportError,
)
from matterloop_tools.mcp.mapper import StructuralMcpResponseMapper
from matterloop_tools.mcp.models import (
    McpCallResult,
    McpCatalog,
    McpContent,
    McpContentKind,
    McpLimits,
    McpPromptArgument,
    McpPromptDefinition,
    McpPromptMessage,
    McpPromptPage,
    McpPromptResult,
    McpResourceDefinition,
    McpResourcePage,
    McpResourceResult,
    McpResourceTemplateDefinition,
    McpResourceTemplatePage,
    McpServerCapabilities,
    McpServerConfig,
    McpToolDefinition,
    McpToolPage,
)
from matterloop_tools.mcp.protocols import McpResponseMapper, McpSessionAdapter
from matterloop_tools.mcp.registry import McpServerRegistry
from matterloop_tools.mcp.sdk_v1 import McpSdkV1SessionAdapter
from matterloop_tools.mcp.tool_adapter import McpToolAdapter, McpToolCaller, safe_mcp_tool_name

__all__ = [
    "McpCallResult",
    "McpCapabilityNotSupportedError",
    "McpCatalog",
    "McpCatalogStaleError",
    "McpConfigurationError",
    "McpContent",
    "McpContentKind",
    "McpError",
    "McpLifecycleError",
    "McpLimits",
    "McpPaginationLimitError",
    "McpPromptArgument",
    "McpPromptDefinition",
    "McpPromptMessage",
    "McpPromptPage",
    "McpPromptResult",
    "McpProtocolError",
    "McpRemoteError",
    "McpResponseLimitError",
    "McpResourceDefinition",
    "McpResourcePage",
    "McpResourceResult",
    "McpResourceTemplateDefinition",
    "McpResourceTemplatePage",
    "McpResponseMapper",
    "McpSdkV1SessionAdapter",
    "McpServerConfig",
    "McpServerCapabilities",
    "McpServerConnection",
    "McpServerNotFoundError",
    "McpServerRegistry",
    "McpSessionAdapter",
    "McpTimeoutError",
    "McpToolAdapter",
    "McpToolCaller",
    "McpToolDefinition",
    "McpToolNameCollisionError",
    "McpToolPage",
    "McpTransportError",
    "StructuralMcpResponseMapper",
    "safe_mcp_tool_name",
]
